import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { copyText } from '../src/scripts/reader-tools.mjs';
const article = await readFile(new URL('../dist/blog/rapid-scramble-with-stable-text/index.html', import.meta.url), 'utf8');
assert.match(article, /aria-label="On this page"/);
assert.match(article, /class="section-anchor"/);
assert.match(article, /class="table-scroll"/);
assert.match(article, /aria-label="Code example, scroll horizontally if needed"/);
assert.match(article, /blob\/main\/src\/content\/blog\/rapid-scramble-with-stable-text.md/);
assert.match(article, /issues\/new\?title=Correction/);
const ids = new Set([...article.matchAll(/\bid="([^"]+)"/g)].map(m => m[1]));
for (const [, id] of article.matchAll(/href="#([^"]+)"/g)) assert.ok(ids.has(id), `Missing fragment ${id}`);
let copied;
assert.equal(await copyText('sample', {}, { clipboard: { writeText: async text => { copied = text; } } }), true);
assert.equal(copied, 'sample');
let restored = false, removed = false, selected = false;
const field = { setAttribute() {}, select() { selected = true; }, remove() { removed = true; } };
const doc = { activeElement: { focus() { restored = true; } }, getSelection: () => null, createElement: () => field, body: { append() {} }, execCommand: () => true };
assert.equal(await copyText('fallback', doc, { clipboard: { writeText: async () => { throw Error('denied'); } } }), true);
assert.equal(field.value, 'fallback'); assert.ok(restored && removed && selected);
doc.execCommand = () => false;
assert.equal(await copyText('manual', doc, {}), false);
doc.execCommand = () => { throw Error('unsupported'); };
assert.equal(await copyText('manual', doc, {}), false);
console.log('PASS: article TOC, anchors, source/correction URLs, accessible overflow; clipboard success, permission-denied fallback, manual failure and focus restoration.');
